### ISSUE TITLE
Use tf_dcos_core instead of keeping a copy in this repo

### ISSUE THREAD

**Issue by luisdavim** [bernadinm/terraform-dcos#7]
Hi, this should use:
```hcl
source  = "git::ssh://git@github.com:bernadinm/tf_dcos_core.git"
```
Instead of:
```hcl
source  = "./modules/dcos-core"
```
and then remove the `/aws/modules/dcos-core/` copy of the `dcos-core` moule from this repo.

**Comment by bernadinm** [comment]
Hi Luis. I have subbed in the tf_dcos_core module so now this repo is pointing to it. Thanks again for your help!! 👍
